version: '3'
services:
  postgresdb:
    image: postgres
    restart: always
    environment:
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
      TZ: UTC
    ports:
      - "5432:5432" # Puedes ajustar el puerto según sea necesario
    volumes:
      - db-data:/var/lib/postgresql/data

  bigpixel-backend:
    build:
      context: . # Ruta a la carpeta del backend
    ports:
      - "4040:4040" # Puedes ajustar el puerto según tu aplicación
    depends_on:
      - postgresdb
    environment:
      - DB_IP=postgresdb
      - DB_PORT=5432
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - .:/project

volumes:
  db-data: